name: auto issue workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: auto issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get runner name
        env:
          RUNNER_NAME: ${{ runner.name }}
      - name: Create issue
        if: env.RUNNER_NAME = "Hosted Runner"
        run: |
          echo ${{ runner.name }}
#          echo ${{ secrets.PAT }} | gh auth login --with-token
#          gh issue create --title "I found a bug" --body "Nothing works" --repo ksato22/secret_test_1
