name: auto issue workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: auto issue
    runs-on: ubuntu-latest
    env:
      CURRENT_RUNNER: ${{ runner.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issue
        if: env.CURRENT_RUNNER = "Hosted Runner"
        run: |
          echo ${{ runner.name }}
#          echo ${{ secrets.PAT }} | gh auth login --with-token
#          gh issue create --title "I found a bug" --body "Nothing works" --repo ksato22/secret_test_1
