name: auto issue workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: auto issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issue
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh issue create --title "I found a bug" --body "Nothing works" --repo ksato22/auto_issue
